// This file contains the change sequences master data

const changeSequences = {
  5: [
    // Start of 5 Bell Rounds Transitions
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Weasels',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    // End of 5 Bell Rounds Transitions
    //Start of 5 Bell Back Rounds Transitions
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Weasels',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    // End of 5 Bell Back Rounds Transitions
    // Start of 5 Bell Queens Transitions
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Weasels',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    // End of 5 Bell Queens Transitions
    // Start of 5 Bell Kings Transitions
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Weasels',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    // End of 5 Bell Kings Transitions
    // Start of 5 Bell Tittums Transitions
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Weasels',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    // End of 5 Bell Tittums Transitions
    // Start of 5 Bell Weasels Transitions
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Rounds',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Queens',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Kings',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Tittums',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    // End of 5 Bell Weasels Transitions
  ],

  // 6 bells
  6: [
    // Start of 6 Bell Rounds Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Rounds Transitions
    // Start of 6 Bell Back Rounds Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Back Rounds Transitions
    // Start of 6 Bell Queens Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Queens Transitions
    // Start of 6 Bell Kings Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [5, 3, 1, 2, 4, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Kings Transitions
    // Start of 6 Bell Tittums Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 4, 2, 5, 3, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Tittums Transitions
    // Start of 6 Bell Exploding Tittums Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [3, 4, 2, 5, 1, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Exploding Tittums Transitions
    // Start of 6 Bell Hagdyke Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Rounds',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Queens',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Kings',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Tittums',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Princes',
      sourceOrder: [3, 4, 1, 2, 5, 6],
      targetOrder: [5, 3, 2, 1, 4, 6],
      sequence: [],
    },
    // End of 6 Bell Hagdyke Transitions
    // Start of 6 Bell Princes Transitions
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [5, 3, 1, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [1, 4, 2, 5, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [3, 4, 2, 5, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 3, 2, 1, 4, 6],
      targetOrder: [3, 4, 1, 2, 5, 6],
      sequence: [],
    },
    // End of 6 Bell Princes Transitions
  ],

  // 8 bells
  8: [
    // Start of 8 Bell Rounds Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Rounds Transitions
    // Start of 8 Bell Back Rounds Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Back Rounds Transitions
    // Start of 8 Bell Roller Coaster Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Rounds',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Queens',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Kings',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Tittums',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Princes',
      sourceOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Roller Coaster Transitions
    // Start of 8 Bell Queens Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Queens Transitions
    // Start of 8 Bell Kings Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Roller Coaster',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Whittingtons',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Kings Transitions
    // Start of 8 Bell Tittums Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Tittums Transitions
    // Start of 8 Bell Exploding Tittums Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Roller Coaster',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Exploding Tittums Transitions
    // Start of 8 Bell Whittingtons Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Rounds',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Whittingtons Transitions
    // Start of 8 Bell Hagdyke Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Rounds',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      sequence: [],
    },
    // End of 8 Bell Hagdyke Transitions
    // Start of 8 Bell Princes Transitions
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Roller Coaster',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [1, 4, 3, 2, 7, 6, 5, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [1, 3, 5, 7, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [7, 5, 3, 1, 2, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [4, 5, 3, 6, 2, 7, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Whittingtons',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [1, 2, 7, 5, 3, 4, 6, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [7, 5, 3, 2, 1, 4, 6, 8],
      targetOrder: [1, 2, 5, 6, 3, 4, 7, 8],
      sequence: [],
    },
    // End of 8 Bell Princes Transitions
  ],

  // 10 bells
  10: [
    // Start of 10 Bell Rounds Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Rounds Transitions
    // Start of 10 Bell Back Rounds Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Back Rounds Transitions
    // Start of 10 Bell Roller Coaster Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Rounds',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Queens',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Kings',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Tittums',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Hagdyke',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Princes',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Roller Coaster',
      targetPattern: 'Princes',
      sourceOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Roller Coaster Transitions
    // Start of 10 Bell Queens Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Queens Transitions
    // Start of 10 Bell Kings Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Roller Coaster',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Kings Transitions
    // Start of 10 Bell Tittums Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Tittums Transitions
    // Start of 10 Bell Exploding Tittums Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Roller Coaster',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },

    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      targetOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      sequence: [],
    },
    // End of 10 Bell Exploding Tittums Transitions
    // Start of 10 Bell Hagdyke Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Rounds',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Roller Coaster',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Queens',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Kings',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Tittums',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },

    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Princes',
      sourceOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      targetOrder: [7, 5, 3, 2, 1, 4, 6, 8, 9, 10],
      sequence: [],
    },
    //End of 10 Bell Hagdyke Transitions
    // Start of 10 Bell Princes Transitions
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Roller Coaster',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [3, 2, 1, 6, 5, 4, 9, 8, 7, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [9, 7, 5, 3, 1, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [1, 6, 2, 7, 3, 8, 4, 9, 5, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [5, 6, 4, 7, 3, 8, 2, 9, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [9, 7, 5, 3, 2, 1, 4, 6, 8, 10],
      targetOrder: [3, 4, 1, 2, 7, 8, 5, 6, 9, 10],
      sequence: [],
    },
    //End of 10 Bell Princes Transitions
  ],

  // 12 bells
  12: [
    // Start of 12 Bell Rounds Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Rounds Transitions
    // Start of 12 Bell Back Rounds Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End 12 Bell Back Rounds Transitions
    // Start of 12 Bell Queens Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Queens Transitions
    //Start of 12 Bell Kings Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Whittingtons',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Kings Transitions
    //Start of 12 Bell Tittums Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Tittums Transitions
    //Start of 12 Bell Exploding Tittums Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Exploding Tittums Transitions
    //Start of 12 Bell Whittingtons Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Rounds',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Queens',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Kings',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Tittums',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Whittingtons',
      targetPattern: 'Princes',
      sourceOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Whittingtons Transitions
    //Start of 12 Bell Hagdyke Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Rounds',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      targetOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      sequence: [],
    },
    //End of 12 Bell Hagdyke Transitions
    //Start of 12 Bell Princes Transitions
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [1, 7, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [6, 7, 5, 8, 4, 9, 3, 10, 2, 11, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Whittingtons',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [5, 3, 1, 2, 4, 6, 11, 9, 7, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [11, 9, 7, 5, 3, 2, 1, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 5, 6, 3, 4, 9, 10, 7, 8, 11, 12],
      sequence: [],
    },
    //End of 12 Bell Princes Transitions
  ],
};
