// This file contains the change sequences needed to transform between patterns
// using the "calling up" style. Each transformation contains:
// - source pattern name and bell order
// - target pattern name and bell order
// - sequence of changes needed

const changeSequences = {
  // 5 bells
  5: [
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Rounds',
      targetPattern: 'Weasels',
      sourceOrder: [1, 2, 3, 4, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Weasels',
      sourceOrder: [4, 3, 2, 1, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Queens',
      targetPattern: 'Weasels',
      sourceOrder: [2, 4, 1, 3, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Kings',
      targetPattern: 'Weasels',
      sourceOrder: [3, 1, 2, 4, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Tittums',
      targetPattern: 'Weasels',
      sourceOrder: [3, 1, 4, 2, 5],
      targetOrder: [1, 4, 2, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Rounds',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [1, 2, 3, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [4, 3, 2, 1, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Queens',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [2, 4, 1, 3, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Kings',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [3, 1, 2, 4, 5],
      sequence: [],
    },
    {
      numberOfBells: 5,
      sourcePattern: 'Weasels',
      targetPattern: 'Tittums',
      sourceOrder: [1, 4, 2, 3, 5],
      targetOrder: [3, 1, 4, 2, 5],
      sequence: [],
    },
  ],

  // 6 bells
  6: [
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 2, 4, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 3, 4, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 4, 3, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [1, 3, 5, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 2, 6, 4],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Rounds',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 2, 3, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Queens',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [2, 4, 1, 3, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Kings',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [3, 1, 2, 4, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [3, 1, 4, 2, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Back Rounds',
      targetPattern: 'Princes',
      sourceOrder: [5, 4, 3, 2, 1, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Back Rounds',
      sourceOrder: [2, 4, 1, 3, 5, 6],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Kings',
      sourceOrder: [2, 4, 1, 3, 5, 6],
      targetOrder: [5, 1, 3, 6, 4, 2],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Tittums',
      sourceOrder: [2, 4, 1, 3, 5, 6],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [2, 4, 1, 3, 5, 6],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [2, 4, 1, 3, 5, 6],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [2, 4, 1, 3, 5, 6],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [5, 4, 3, 2, 1, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [2, 4, 1, 3, 5, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 5, 2, 3, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 5, 2, 4, 3, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 5, 3, 2, 4, 6],
      sequence: [],
    },
    {
      numberOfBells: 6,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [5, 1, 3, 6, 4, 2],
      targetOrder: [1, 3, 5, 2, 6, 4],
      sequence: [],
    },
  ],

  // 8 bells
  8: [
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      targetOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Tittums',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      targetOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [7, 6, 5, 4, 3, 2, 1, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [5, 1, 3, 6, 4, 2, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8],
      sequence: [],
    },
    {
      numberOfBells: 8,
      sourcePattern: 'Princes',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 3, 5, 2, 6, 4, 7, 8],
      targetOrder: [1, 3, 5, 2, 4, 6, 7, 8],
      sequence: [],
    },
  ],

  // 10 bells
  10: [
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Tittums',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Tittums',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Hagdyke',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Rounds',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [9, 8, 7, 6, 5, 4, 3, 2, 1, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Queens',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Kings',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [9, 1, 3, 5, 7, 2, 4, 6, 8, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Tittums',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10],
      sequence: [],
    },
    {
      numberOfBells: 10,
      sourcePattern: 'Princes',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 3, 5, 7, 9, 2, 6, 4, 8, 10],
      targetOrder: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      sequence: [],
    },
  ],

  // 12 bells
  12: [
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Roller Coaster',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 5, 2, 6, 3, 7, 4, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Queens',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Kings',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Rounds',
      targetPattern: 'Princes',
      sourceOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 6, 4, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Queens',
      targetPattern: 'Princes',
      sourceOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 6, 4, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Rounds',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Back Rounds',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Queens',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Tittums',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Hagdyke',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Kings',
      targetPattern: 'Princes',
      sourceOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 6, 4, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Kings',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 9, 7, 5, 3, 1, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Exploding Tittums',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Whittingtons',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Hagdyke',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 5, 3, 2, 4, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Tittums',
      targetPattern: 'Princes',
      sourceOrder: [1, 5, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 6, 4, 8, 10, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Back Rounds',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 12],
      sequence: [],
    },
    {
      numberOfBells: 12,
      sourcePattern: 'Exploding Tittums',
      targetPattern: 'Queens',
      sourceOrder: [1, 5, 2, 4, 3, 6, 7, 8, 9, 10, 11, 12],
      targetOrder: [1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
      sequence: [],
    },
  ],
};

// Helper function to find a specific transformation
function findTransformation(bellCount, sourcePattern, targetPattern) {
  return changeSequences[bellCount].find(
    t => t.sourcePattern === sourcePattern && t.targetPattern === targetPattern
  );
}

// Export the change sequences and helper function for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    changeSequences,
    findTransformation,
  };
}
